version: '2'
services:
    postgres_calc:
        container_name: postgres_calc
        image: postgres
        restart: always
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: calc
        volumes:
          - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local