"""

Revision ID: 363c11edf7ec
Revises: 
Create Date: 2023-05-21 23:17:58.254213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363c11edf7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA health")
    op.create_table('bmi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('classify', sa.Enum('THINNESS', 'OVERWEIGHT', 'OBESITY', 'SERIUS_OBESITY', name='bmiclassify'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bmi')),
    schema='health'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bmi', schema='health')
    op.execute("DROP SCHEMA health")
    op.execute("DROP TYPE bmiclassify")
    # ### end Alembic commands ###
